### PR TITLE
install python3.8

### PR DESCRIPTION
**Pull request by jburel**
Build artifacts using python 3.8
cc @sbesson

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
LGTM
The former release assets can still be used for people needing Python 3.6 but switching to Python 3.8 which is natively packaged makes complete sense given the Python timeline - https://endoflife.date/python.

**Comment by jburel** [comment]
Merging and tagging as 0.0.2

**Comment by sbesson** [comment]
0.1.0?

**Comment by jburel** [comment]
yes 0.0.2 was for my test.

**Pull request merged**
